---
tabWidth: 4
printWidth: 120
semi: false
singleQuote: true
quoteProps: consistent
jsxSingleQuote: true
trailingComma: all
bracketSpacing: true
jsxBracketSameLine: true
arrowParens: avoid
proseWrap: always
